openapi: 3.0.1
info:
  title: VNPT API Tenant
  description: |-
    ## VNPT API Reference : VNPT 001 - Tenant 

    ### Release : 1.1.0

    Description about Tenant

    ### Resources
    - Tenant

    Tenant API performs the following operations :
    - Retrieve an tenant
    - Retrieve a collection of tenants according to given criteria
    - Create a new tenant
    - Update an existing tenant
  version: 1.1.0
servers:
  - url: https://serverRoot/vnpt-api/tenant/v1/
tags:
  - name: tenant
paths:
  /tenant:
    get:
      tags:
        - tenant
      summary: List or find Tenant objects
      description: This operation list or find Tenant entities
      operationId: listTenant
      parameters:
        - name: fields
          in: query
          description: Comma-separated properties to be provided in response
          schema:
            type: string
        - name: offset
          in: query
          description: Requested index for start of resources to be provided in response
          schema:
            type: integer
        - name: limit
          in: query
          description: Requested number of resources to be provided in response
          schema:
            type: integer
      responses:
        '200':
          description: Success
          headers:
            X-Total-Count:
              description: Total number of items matching criteria
              schema:
                type: integer
            X-Result-Count:
              description: Actual number of items returned in the response body
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tenant'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - tenant
      summary: Creates a Tenant
      description: This operation creates a Tenant entity.
      operationId: createTenant
      requestBody:
        description: The Tenant to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant_Create'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: Tenant
  /tenant/{id}:
    get:
      tags:
        - tenant
      summary: Retrieves a Tenant by ID
      description: This operation retrieves a Tenant entity. Attribute selection is enabled for all first level attributes.
      operationId: retrieveTenant
      parameters:
        - name: id
          in: path
          description: Identifier of the Tenant
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: Comma-separated properties to provide in response
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - tenant
      summary: Updates partially a Tenant
      description: This operation updates partially a Tenant entity.
      operationId: patchTenant
      parameters:
        - name: id
          in: path
          description: Identifier of the Tenant
          required: true
          schema:
            type: string
      requestBody:
        description: The Tenant to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tenant_Update'
        required: true
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tenant'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '405':
          description: Method Not allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: Tenant
components:
  schemas:
    Tenant:
      type: object
      properties:
        id:
          type: string
          description: unique identifier
        usePackage:
          type: string
        domainName:
          type: string
          description: Use a domain for your organization, in the format (example.com). This domain should be unique.
          format: uri
        isActive:
          type: boolean
          description: A “true” value specifies tenant active
        createdDate:
          type: string
          description: Date of create
          format: date-time
        updatedDate:
          type: string
          description: Last update
          format: date-time
        userConfig:
          $ref: '#/components/schemas/Userinfo'
      description: Tenant represents a single zone independen with other.
    Tenant_Create:
      required:
        - domainName
        - userConfig
      type: object
      properties:
        domainName:
          type: string
          description: Use a domain for your organization, in the format (example.com). This domain should be unique.
        usePackage:
          type: string
        isActive:
          type: boolean
          description: A “true” value specifies tenant active
        userConfig:
          $ref: '#/components/schemas/Userinfo'
      description: |-
        Tenant represents a single zone independen with other.
        Skipped properties: id,href
    Tenant_Update:
      required:
        - domainName
        - userConfig
      type: object
      properties:
        domainName:
          type: string
          description: Use a domain for your organization, in the format (example.com). This domain should be unique.
        usePackage:
          type: string
        isActive:
          type: boolean
          description: A “true” value specifies tenant active
        userConfig:
          $ref: '#/components/schemas/Userinfo'
      description: |-
        Individual represents a single zone independen with other.
        Skipped properties: id,href
    Userinfo:
      type: object
      required:
        - name
        - userName
        - email
      properties:
        email:
          example: jane.doe@email.com
          type: string
          description: Full email address in standard format
        name:
          example: Jane Mary Doe
          type: string
          description: >-
            End-User's full name in displayable form including all name parts,
            possibly including titles and suffixes, ordered according to the
            End-User's locale and preferences
        userName:
          type: string
          description: Subject - Unique Identifier for the End-User

    Error:
      required:
        - code
        - reason
      type: object
      properties:
        code:
          type: string
          description: Application relevant detail, defined in the API or a common list.
        reason:
          type: string
          description: Explanation of the reason for the error which can be shown to a client user.
        message:
          type: string
          description: More details and corrective actions related to the error which can be shown to a client user.
        status:
          type: string
          description: HTTP Error code extension
        referenceError:
          type: string
          description: URI of documentation describing the error.
          format: uri
        '@baseType':
          type: string
          description: When sub-classing, this defines the super-class.
        '@schemaLocation':
          type: string
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
          format: uri
        '@type':
          type: string
          description: When sub-classing, this defines the sub-class entity name.
      description: Used when an API throws an Error, typically with a HTTP error response-code (3xx, 4xx, 5xx)
x-original-swagger-version: '2.0'