spring:
    profiles:
        active: mysql
#        active: mongo
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    data:
        mongodb:
            database: service_inventory
            uri: mongodb://localhost:27017/service_inventory
    datasource:
        url: jdbc:mysql://localhost:3306/serviceInvtory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: rootpassword
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
    jpa:
        packages-to-scan: oda.sid.tmf.model
        hibernate:
            ddl-auto: update
        show-sql: true
        generate_statistics: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    jackson:
        serialization:
            write-dates-as-timestamps:  false
logging:
    level:
        org.hibernate.orm.jdbc.bind: TRACE